(define (square x)
  (* x x))
(define (sum-sq x y)
  (+ (square x) (square y)))
(define (sum-top2 x y z)
  (cond ((and (>= x y) (>= y z)) (sum-sq x y))
        ((and (>= x y) (>= z y)) (sum-sq x z))
        ((and (>= y x) (>= x z)) (sum-sq x y))
        ((and (>= y x) (>= z x)) (sum-sq y z))))
